### ISSUE TITLE
Suggestions!

### ISSUE THREAD

**Issue by willcastillo** [askerakbar/gpt-trix-editor#10]
Hey, thanks for this plugin!

I have a couple of suggestions I hope you accept and implement:
- It'd be great if there were a config setting that we can send as [a system message](https://help.openai.com/en/articles/8234522-chat-completions-api-system-message-vs-custom-instructions-in-ui) to the model
- It'd also be great if the plugin dispatches an event with every response it gets and finally...
- It'd be great if we can specify additional context to an action. That is, modifying the content sent to the model, something like a filter. Imagine a closure like `->additionalContext( function (Model $record) { return $record->metadata; }` and then you prepend this to your current content variable. 

With these three suggestions working in tandem, we'll do wonders in the text editor:
-  We (the consumers of the plugin, the devs) we'll be able to inject any context we want and create powerful actions not dependent on the editor's content.
- We'll be able to, thru the use of a system message, define the tone, persona and other general characteristics we'd like our action to have.

Again, thanks lot for this plugin!

**Comment by askerakbar** [comment]
Thanks for your suggestions! 
I'm quite busy with my office work currently, but I'll consider these ideas when I have more free time on weekends. 

Again thanks!
