### ISSUE TITLE
error on install 

### ISSUE THREAD

**Issue by alfonsin1** [askerakbar/gpt-trix-editor#7]
λ composer require askerakbar/gpt-trix-editor
./composer.json has been updated
Running composer update askerakbar/gpt-trix-editor
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - askerakbar/gpt-trix-editor[1.0.0, ..., 1.0.1] require filament/filament ^2.0 -> found filament/filament[v2.0.0-beta1, ..., 2.x-dev] but it conflicts with your root composer.json require (^3.2).
    - askerakbar/gpt-trix-editor[dev-main, 2.0.0] require illuminate/contracts ^9.0|^10.0 -> found illuminate/contracts[v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires askerakbar/gpt-trix-editor * -> satisfiable by askerakbar/gpt-trix-editor[dev-main, 1.0.0, 1.0.1, 2.0.0, 9999999-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require askerakbar/gpt-trix-editor:*" to figure out if any version is installable, or "composer require askerakbar/gpt-trix-editor:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by craigvc** [comment]
@alfonsin1 I fixed this in my pull request.

**Comment by StaffCollab** [comment]
I have the same issue.

Can @askerakbar accept @alfonsin1 pull request?

**Comment by askerakbar** [comment]
done.
